[package]
name = "hl7-mllp-codec"
description = "A Tokio codec for HL7 Minimal Lower Layer Message Transport protocol (MLLP)"
version = "0.0.1"
authors = ["wokket <wokket@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/wokket/hl7-mllp-codec"
categories = ["asynchronous", "network-programming"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
tokio = "0.2.0-alpha.6"